[default.extend-words]
ser = "ser"
Referer = "Referer"
Encryp = "Encryp"
OT = "OT"
Wheres = "Wheres"
ws = "ws"
guid = "guid"
yoy = "yoy"
Ein = "Ein"
cpy1 = "cpy1"
cpy2 = "cpy2"
getCellDatas = "getCellDatas"
[files]
extend-exclude = ["mapFiles/**", "docs"]
