import type { MenuConfig } from '@univerjs/ui'

const PREVIEW_HIDDEN_MENU_IDS = [
  'sheet.command.cut',
  'sheet.command.paste',
  'sheet.menu.paste-special',
  'sheet.command.paste-value',
  'sheet.command.paste-format',
  'sheet.command.paste-col-width',
  'sheet.command.paste-besides-border',
  'sheet.menu.clear-selection',
  'sheet.contextMenu.text-to-number',
  'sheet.menu.cell-insert',
  'sheet.menu.delete',
  'sheet.menu.sheet-frozen',
  'sheet.column-header-menu.sheet-frozen',
  'sheet.row-header-menu.sheet-frozen',
  'sheet.contextMenu.permission',
  'sheet.command.insert-multi-cols-before',
  'sheet.command.insert-multi-cols-right',
  'sheet.command.insert-multi-rows-above',
  'sheet.command.insert-multi-rows-after',
  'sheet.command.hide-col-confirm',
  'sheet.command.hide-row-confirm',
  'sheet.command.set-selected-cols-visible',
  'sheet.command.set-selected-rows-visible',
  'sheet.command.remove-col-confirm',
  'sheet.command.remove-row-confirm',
  'sheet.command.remove-sheet-confirm',
  'sheet.command.copy-sheet',
  'sheet.operation.rename-sheet',
  'sheet.command.set-tab-color',
  'sheet.command.set-worksheet-hidden',
  'sheet.menu.sheets-sort',
  'sheet.menu.sheets-sort-ctx',
  'sheet.menu.data-validation',
  'sheet.operation.open-table-selector',
  'sheet.table.context-insert_menu-id',
  'sheet.table.context-remove_menu-id',
  'sheet.operation.insert-hyper-link',
  'sheet.operation.insert-hyper-link-toolbar',
  'dataease.operation.paste-plugin-table',
  'sheet.operation.add-note-popup',
  'sheet.command.delete-note',
  'sheet.command.toggle-note-popup',
  'sheet.command.add-range-protection-from-sheet-bar',
  'sheet.command.add-range-protection-from-context-menu',
  'sheet.command.set-range-protection-from-context-menu',
  'sheet.command.delete-range-protection-from-context-menu',
  'sheet.command.view-sheet-permission-from-context-menu',
  'sheet.command.delete-worksheet-protection-from-sheet-bar',
  'sheet.command.change-sheet-protection-from-sheet-bar',
  'sheet.command.view-sheet-permission-from-sheet-bar'
]

export const PREVIEW_MENU_CONFIG: MenuConfig = Object.fromEntries(
  PREVIEW_HIDDEN_MENU_IDS.map(id => [id, { hidden: true }])
)
