export const  proxyMapping = {
    'c3dpdGNoZXI=': '/component/switcher/index',
    'dWNlbnRlci1oYW5kbGVy': '/component/menu-handler/UcenterHandler',
    'ZGF0YXNldC1yb3ctcGVybWlzc2lvbnM=': '/component/row-col-permission/dataset-row-permissions/index',
    'ZGF0YXNldC1yb3ctcGVybWlzc2lvbnMtaW5mbw==': '/component/row-col-permission/dataset-row-permissions-info/index',
    'ZGF0YXNldC1jb2x1bW4tcGVybWlzc2lvbnM=': '/component/row-col-permission/dataset-column-permissions/index',
    'ZGF0YXNldC1jb2x1bW4tcGVybWlzc2lvbnMtaW5mbw==': '/component/row-col-permission/dataset-column-permissions-info/index',
    'L2NvbXBvbmVudC9sb2dpbi9IYW5kbGVy': '/component/login/Handler',
    'L21lbnUvc3lzdGVtL21lbWJlci9pbmRleA==': '/menu/system/member/index',
    'L21lbnUvc3lzdGVtL29yZy9pbmRleA==': '/menu/system/org/index',
    'L21lbnUvc3lzdGVtL2F1dGgvaW5kZXg=': '/menu/system/auth/index',
    'L21lbnUvdXNlci1jZW50ZXIvaW5kZXg=': '/menu/user-center/index',
    'L21lbnUvc2V0dGluZy9hdXRoZW50aWNhdGlvbi9pbmRleA==': '/menu/setting/authentication/index',
    'L21lbnUvc3lzdGVtL3N5bmMvc3VtbWFyeS9pbmRleA==': '/menu/system/sync/summary/index',
    'L21lbnUvc3lzdGVtL3N5bmMvZHMvaW5kZXg=': '/menu/system/sync/ds/index',
    'L21lbnUvc3lzdGVtL3N5bmMvdGFzay9pbmRleA==': '/menu/system/sync/task/index',
    'L21lbnUvc2V0dGluZy9lbWJlZGRlZC9pbmRleA==': '/menu/setting/embedded/index',
    'L21lbnUvc2V0dGluZy9wbGF0Zm9ybS9pbmRleA==': '/menu/setting/platform/index',
    'L21lbnUvc2V0dGluZy92YXJpYWJsZS9pbmRleA==': '/menu/setting/variable/index',
    'L2NvbXBvbmVudC9yb3ctY29sLXBlcm1pc3Npb24vcGFuZS9pbmRleA==': '/component/row-col-permission/pane/index',
    'L21lbnUvYXBpZG9jL2luZGV4': '/menu/apidoc/index',
    'L21lbnUvc3lzdGVtL2xvZy9pbmRleA==': '/menu/system/log/index',
    'L21lbnUvc3lzdGVtL3dhdGVybWFyay9pbmRleA==': '/menu/system/watermark/index',
    'L21lbnUvc2V0dGluZy9hcHBlYXJhbmNlL2luZGV4': '/menu/setting/appearance/index',
    'L2NvbXBvbmVudC9lbWJlZGRlZC1pZnJhbWUvRW50cmFuY2Vz': '/component/embedded-iframe/Entrances',
    'L2NvbXBvbmVudC9lbWJlZGRlZC1pZnJhbWUvT3BlbkhhbmRsZXI=': '/component/embedded-iframe/OpenHandler',
    'L2NvbXBvbmVudC9lbWJlZGRlZC1pZnJhbWUvTmV3V2luZG93SGFuZGxlcg==': '/component/embedded-iframe/NewWindowHandler',
    'L21lbnUvc3lzdGVtL3JlcG9ydC9pbmRleA==': '/menu/system/report/index',
    'L21lbnUvc2V0dGluZy9lbWFpbC9pbmRleA==': '/menu/setting/email/index',
    'L2NvbXBvbmVudC9tZW51LWhhbmRsZXIvRW1haWxIYW5kbGVy': '/component/menu-handler/EmailHandler',
    'L2NvbXBvbmVudC9sb2dpbi9JbnZhbGlkUHdk': '/component/login/InvalidPwd',
    'L2NvbXBvbmVudC9sb2dpbi9Qd2RJbnZhbGlkVGlwcw==': '/component/login/PwdInvalidTips',
    'L21lbnUvc2V0dGluZy9wbHVnaW4vaW5kZXg=': '/menu/setting/plugin/index',
    'L2NvbXBvbmVudC9wbHVnaW5zLWhhbmRsZXIvVmlld0NhdGVnb3J5SGFuZGxlcg==': '/component/plugins-handler/ViewCategoryHandler',
    'L2NvbXBvbmVudC9wbHVnaW5zLWhhbmRsZXIvRHNDYXRlZ29yeUhhbmRsZXI=': '/component/plugins-handler/DsCategoryHandler',
    'L2NvbXBvbmVudC9wbHVnaW5zLWhhbmRsZXIvRGZDYXRlZ29yeUhhbmRsZXI=': '/component/plugins-handler/DfCategoryHandler',
    'L2NvbXBvbmVudC9kYXRhLWZpbGxpbmcvRGF0YXNvdXJjZUVuYWJsZURhdGFGaWxsaW5n':'/component/data-filling/DatasourceEnableDataFilling',
    'L2NvbXBvbmVudC9kYXRhLWZpbGxpbmcvRGF0YXNvdXJjZURhdGFGaWxsaW5nSW5mbw==':'/component/data-filling/DatasourceDataFillingInfo',
    'L21lbnUvZGF0YS9kYXRhLWZpbGxpbmcvbWFuYWdlL2luZGV4':'/menu/data/data-filling/manage/index',
    'L21lbnUvZGF0YS9kYXRhLWZpbGxpbmcvbWFuYWdlL2Zvcm0vaW5kZXg=':'/menu/data/data-filling/manage/form/index',
    'L21lbnUvZGF0YS9kYXRhLWZpbGxpbmcvbWFuYWdlL2Zvcm0vRGF0YUZpbGxpbmdGb3JtU2F2ZQ==':'/menu/data/data-filling/manage/form/DataFillingFormSave',
    'L21lbnUvZGF0YS9kYXRhLWZpbGxpbmcvbWFuYWdlL0NyZWF0RHNHcm91cA==':'/menu/data/data-filling/manage/CreatDsGroup',
    'L21lbnUvZGF0YS9kYXRhLWZpbGxpbmcvbWFuYWdlL2Zvcm0vUm93RGF0YUZvcm0=':'/menu/data/data-filling/manage/form/RowDataForm',
    'L21lbnUvZGF0YS9kYXRhLWZpbGxpbmcvbWFuYWdlL2Zvcm0vRnJlcXVlbmN5Rm9ybQ==':'/menu/data/data-filling/manage/form/FrequencyForm',
    'L21lbnUvZGF0YS9kYXRhLWZpbGxpbmcvbWFuYWdlL2Zvcm0vQmFzZVJlY2lwaWVudEZvcm0=':'/menu/data/data-filling/manage/form/BaseRecipientForm',
    'L21lbnUvZGF0YS9kYXRhLWZpbGxpbmcvZmlsbC9UYWJQYW5l':'/menu/data/data-filling/fill/TabPane',
    'L21lbnUvZGF0YS9kYXRhLWZpbGxpbmcvZmlsbC9UYWJQYW5lVGFibGU=':'/menu/data/data-filling/fill/TabPaneTable',
    'L2NvbXBvbmVudC90aHJlc2hvbGQtd2FybmluZy9FZGl0QmFySGFuZGxlcg==': '/component/threshold-warning/EditBarHandler',
    'L2NvbXBvbmVudC90aHJlc2hvbGQtd2FybmluZy9UaHJlc2hvbGREaWFsb2c=': '/component/threshold-warning/ThresholdDialog',
    'L21lbnUvc3lzdGVtL3RocmVzaG9sZC9pbmRleA==': '/menu/system/threshold/index',
    'L21lbnUvc3lzdGVtL2Fzc29jaWF0aW9uL2luZGV4': '/menu/system/association/index',
    'L21lbnUvc3lzdGVtL2Fzc29jaWF0aW9uL0NoYXJ0': '/menu/system/association/Chart',
    'L2NvbXBvbmVudC90aHJlc2hvbGQtd2FybmluZy9TZW5pb3JIYW5kbGVy': '/component/threshold-warning/SeniorHandler',
    'L21lbnUvZGF0YS9kYXRhLWZpbGxpbmcvZmlsbC9Nc2dGaWxsVGFibGU=': '/menu/data/data-filling/fill/MsgFillTable',
    'L21lbnUvc2V0dGluZy9zZWN1cml0eS9pbmRleA==': '/menu/setting/security/index',
    'L2NvbXBvbmVudC9kYXRhc2V0L2luZGV4': '/component/dataset/index',
    'L2NvbXBvbmVudC9sb2dpbi9NZmFTdGVw': '/component/login/MfaStep',
    'L21lbnUvc3lzdGVtL3dlYmhvb2svaW5kZXg=': '/menu/system/webhook/index',
    'L2NvbXBvbmVudC9sb2dpbi9Nb2JpbGVIYW5kbGVy': '/component/login/MobileHandler',
    'L21lbnUvc3lzdGVtL3N5c3VzZXIvaW5kZXg=': '/menu/system/sysuser/index',
    'L2NvbXBvbmVudC9lbWJlZGRlZC1pZnJhbWUvSWZyYW1lU2VsZg==': '/component/embedded-iframe/IframeSelf',
    'L21lbnUvc3ByZWFkc2hlZXQ=': '/menu/spreadsheet/index',
    'L21lbnUvc3ByZWFkc2hlZXQtZWRpdG9y': '/menu/spreadsheet/editor',
    'L3Rvb2xzL0htYWNUb29s': '/tools/HmacTool',
    'L2NvbXBvbmVudC9wcm94eS13YXJuL2luZGV4': '/component/proxy-warn/index'
}
