export interface GeometryFrom {
  pid?: string
  code?: string
  name?: string
  fileName?: string
  country?: string
}

/**
 * 国家信息接口
 */
export interface CountryInfo {
  name: string
  cn_name: string
  code: string
  iso_alpha3?: string | null
}

/**
 * 国家列表，包含英文名称、中文名称、数字代码和 ISO Alpha-3 代码
 * 北塞浦路斯、锡亚琴冰川、克什米尔 不是 ISO 3166-1 标准中的主权国家，因此 iso_alpha3 设为 null。
 * 英文名称采用了 ISO 3166-1 标准短名称。
 */
export const countryList: CountryInfo[] = [
  { name: 'Somalia', cn_name: '索马里', code: '706' },
  { name: 'Liechtenstein', cn_name: '列支敦士登', code: '438' },
  { name: 'Morocco', cn_name: '摩洛哥', code: '504' },
  { name: 'Western Sahara', cn_name: '西撒哈拉', code: '732' },
  { name: 'Serbia', cn_name: '塞尔维亚', code: '688' },
  { name: 'Afghanistan', cn_name: '阿富汗', code: '004' },
  { name: 'Angola', cn_name: '安哥拉', code: '024' },
  { name: 'Albania', cn_name: '阿尔巴尼亚', code: '008' },
  { name: 'Andorra', cn_name: '安道尔', code: '020' },
  { name: 'United Arab Emirates', cn_name: '阿联酋', code: '784' },
  { name: 'Argentina', cn_name: '阿根廷', code: '032' },
  { name: 'Armenia', cn_name: '亚美尼亚', code: '051' },
  { name: 'American Samoa', cn_name: '美属萨摩亚', code: '016' },
  { name: 'French Southern Territories', cn_name: '法属南部领地', code: '260' },
  { name: 'Antigua and Barbuda', cn_name: '安提瓜和巴布达', code: '028' },
  { name: 'Australia', cn_name: '澳大利亚', code: '036' },
  { name: 'Austria', cn_name: '奥地利', code: '040' },
  { name: 'Azerbaijan', cn_name: '阿塞拜疆', code: '031' },
  { name: 'Burundi', cn_name: '布隆迪', code: '108' },
  { name: 'Belgium', cn_name: '比利时', code: '056' },
  { name: 'Benin', cn_name: '贝宁', code: '204' },
  { name: 'Burkina Faso', cn_name: '布基纳法索', code: '854' },
  { name: 'Bangladesh', cn_name: '孟加拉国', code: '050' },
  { name: 'Bulgaria', cn_name: '保加利亚', code: '100' },
  { name: 'Bahrain', cn_name: '巴林', code: '048' },
  { name: 'Bahamas', cn_name: '巴哈马', code: '044' },
  { name: 'Bosnia and Herzegovina', cn_name: '波斯尼亚和黑塞哥维那', code: '070' },
  { name: 'Belarus', cn_name: '白俄罗斯', code: '112' },
  { name: 'Belize', cn_name: '伯利兹', code: '084' },
  { name: 'Bermuda', cn_name: '百慕大', code: '060' },
  { name: 'Bolivia', cn_name: '玻利维亚', code: '068' },
  { name: 'Brazil', cn_name: '巴西', code: '076' },
  { name: 'Barbados', cn_name: '巴巴多斯', code: '052' },
  { name: 'Brunei Darussalam', cn_name: '文莱', code: '096' },
  { name: 'Bhutan', cn_name: '不丹', code: '064' },
  { name: 'Botswana', cn_name: '博茨瓦纳', code: '072' },
  { name: 'Central African Republic', cn_name: '中非共和国', code: '140' },
  { name: 'Canada', cn_name: '加拿大', code: '124' },
  { name: 'Switzerland', cn_name: '瑞士', code: '756' },
  { name: 'Chile', cn_name: '智利', code: '152' },
  { name: 'China', cn_name: '中国', code: '156' },
  { name: "Côte d'Ivoire", cn_name: '科特迪瓦', code: '384' },
  { name: 'Cameroon', cn_name: '喀麦隆', code: '120' },
  { name: 'Democratic Republic of the Congo', cn_name: '刚果（金）', code: '180' },
  { name: 'Republic of the Congo', cn_name: '刚果（布）', code: '178' },
  { name: 'Colombia', cn_name: '哥伦比亚', code: '170' },
  { name: 'Comoros', cn_name: '科摩罗', code: '174' },
  { name: 'Cabo Verde', cn_name: '佛得角', code: '132' },
  { name: 'Costa Rica', cn_name: '哥斯达黎加', code: '188' },
  { name: 'Cuba', cn_name: '古巴', code: '192' },
  { name: 'Curaçao', cn_name: '库拉索', code: '531' },
  { name: 'Cayman Islands', cn_name: '开曼群岛', code: '136' },
  { name: 'Cyprus', cn_name: '塞浦路斯', code: '196' },
  { name: 'Czechia', cn_name: '捷克', code: '205' },
  { name: 'Germany', cn_name: '德国', code: '276' },
  { name: 'Djibouti', cn_name: '吉布提', code: '262' },
  { name: 'Dominica', cn_name: '多米尼克', code: '212' },
  { name: 'Denmark', cn_name: '丹麦', code: '208' },
  { name: 'Dominican Republic', cn_name: '多米尼加', code: '214' },
  { name: 'Algeria', cn_name: '阿尔及利亚', code: '012' },
  { name: 'Ecuador', cn_name: '厄瓜多尔', code: '218' },
  { name: 'Egypt', cn_name: '埃及', code: '818' },
  { name: 'Eritrea', cn_name: '厄立特里亚', code: '232' },
  { name: 'Spain', cn_name: '西班牙', code: '724' },
  { name: 'Estonia', cn_name: '爱沙尼亚', code: '233' },
  { name: 'Ethiopia', cn_name: '埃塞俄比亚', code: '231' },
  { name: 'Finland', cn_name: '芬兰', code: '246' },
  { name: 'Fiji', cn_name: '斐济', code: '242' },
  { name: 'Falkland Islands (Malvinas)', cn_name: '福克兰群岛', code: '238' },
  { name: 'French Guiana', cn_name: '法属圭亚那', code: '254' },
  { name: 'France', cn_name: '法国', code: '250' },
  { name: 'Faroe Islands', cn_name: '法罗群岛', code: '234' },
  { name: 'Micronesia, Federated States of', cn_name: '密克罗尼西亚', code: '583' },
  { name: 'Gabon', cn_name: '加蓬', code: '266' },
  { name: 'United Kingdom of Great Britain and Northern Ireland', cn_name: '英国', code: '826' },
  { name: 'Georgia', cn_name: '格鲁吉亚', code: '268' },
  { name: 'Ghana', cn_name: '加纳', code: '288' },
  { name: 'Guinea', cn_name: '几内亚', code: '324' },
  { name: 'Gambia', cn_name: '冈比亚', code: '270' },
  { name: 'Guinea-Bissau', cn_name: '几内亚比绍', code: '624' },
  { name: 'Equatorial Guinea', cn_name: '赤道几内亚', code: '226' },
  { name: 'Greece', cn_name: '希腊', code: '300' },
  { name: 'Grenada', cn_name: '格林纳达', code: '308' },
  { name: 'Greenland', cn_name: '格陵兰', code: '304' },
  { name: 'Guatemala', cn_name: '危地马拉', code: '320' },
  { name: 'Guam', cn_name: '关岛', code: '316' },
  { name: 'Guyana', cn_name: '圭亚那', code: '328' },
  { name: 'Heard Island and McDonald Islands', cn_name: '赫德岛和麦克唐纳群岛', code: '334' },
  { name: 'Honduras', cn_name: '洪都拉斯', code: '340' },
  { name: 'Croatia', cn_name: '克罗地亚', code: '191' },
  { name: 'Haiti', cn_name: '海地', code: '332' },
  { name: 'Hungary', cn_name: '匈牙利', code: '348' },
  { name: 'Indonesia', cn_name: '印度尼西亚', code: '360' },
  { name: 'Isle of Man', cn_name: '马恩岛', code: '833' },
  { name: 'India', cn_name: '印度', code: '356' },
  { name: 'British Indian Ocean Territory', cn_name: '英属印度洋领地', code: '086' },
  { name: 'Ireland', cn_name: '爱尔兰', code: '372' },
  { name: 'Iran, Islamic Republic of', cn_name: '伊朗', code: '364' },
  { name: 'Iraq', cn_name: '伊拉克', code: '368' },
  { name: 'Iceland', cn_name: '冰岛', code: '352' },
  { name: 'Israel', cn_name: '以色列', code: '376' },
  { name: 'Italy', cn_name: '意大利', code: '380' },
  { name: 'Jamaica', cn_name: '牙买加', code: '388' },
  { name: 'Jordan', cn_name: '约旦', code: '400' },
  { name: 'Japan', cn_name: '日本', code: '392' },
  { name: 'Kazakhstan', cn_name: '哈萨克斯坦', code: '398' },
  { name: 'Kenya', cn_name: '肯尼亚', code: '404' },
  { name: 'Kyrgyzstan', cn_name: '吉尔吉斯斯坦', code: '417' },
  { name: 'Cambodia', cn_name: '柬埔寨', code: '116' },
  { name: 'Kiribati', cn_name: '基里巴斯', code: '296' },
  { name: 'Republic of Korea', cn_name: '韩国', code: '410' },
  { name: 'Kuwait', cn_name: '科威特', code: '414' },
  { name: "Lao People's Democratic Republic", cn_name: '老挝', code: '418' },
  { name: 'Lebanon', cn_name: '黎巴嫩', code: '422' },
  { name: 'Liberia', cn_name: '利比里亚', code: '430' },
  { name: 'Libya', cn_name: '利比亚', code: '434' },
  { name: 'Saint Lucia', cn_name: '圣卢西亚', code: '662' },
  { name: 'Sri Lanka', cn_name: '斯里兰卡', code: '144' },
  { name: 'Lesotho', cn_name: '莱索托', code: '426' },
  { name: 'Lithuania', cn_name: '立陶宛', code: '440' },
  { name: 'Luxembourg', cn_name: '卢森堡', code: '442' },
  { name: 'Latvia', cn_name: '拉脱维亚', code: '428' },
  { name: 'Moldova, Republic of', cn_name: '摩尔多瓦', code: '498' },
  { name: 'Madagascar', cn_name: '马达加斯加', code: '450' },
  { name: 'Mexico', cn_name: '墨西哥', code: '484' },
  { name: 'North Macedonia', cn_name: '北马其顿', code: '807' },
  { name: 'Mali', cn_name: '马里', code: '466' },
  { name: 'Malta', cn_name: '马耳他', code: '470' },
  { name: 'Myanmar', cn_name: '缅甸', code: '104' },
  { name: 'Montenegro', cn_name: '黑山', code: '499' },
  { name: 'Mongolia', cn_name: '蒙古', code: '496' },
  { name: 'Northern Mariana Islands', cn_name: '北马里亚纳群岛', code: '580' },
  { name: 'Mozambique', cn_name: '莫桑比克', code: '508' },
  { name: 'Mauritania', cn_name: '毛里塔尼亚', code: '478' },
  { name: 'Montserrat', cn_name: '蒙特塞拉特', code: '500' },
  { name: 'Mauritius', cn_name: '毛里求斯', code: '480' },
  { name: 'Malawi', cn_name: '马拉维', code: '454' },
  { name: 'Malaysia', cn_name: '马来西亚', code: '458' },
  { name: 'Namibia', cn_name: '纳米比亚', code: '516' },
  { name: 'New Caledonia', cn_name: '新喀里多尼亚', code: '540' },
  { name: 'Niger', cn_name: '尼日尔', code: '562' },
  { name: 'Nigeria', cn_name: '尼日利亚', code: '566' },
  { name: 'Nicaragua', cn_name: '尼加拉瓜', code: '558' },
  { name: 'Niue', cn_name: '纽埃', code: '570' },
  { name: 'Netherlands', cn_name: '荷兰', code: '528' },
  { name: 'Norway', cn_name: '挪威', code: '578' },
  { name: 'Nepal', cn_name: '尼泊尔', code: '524' },
  { name: 'New Zealand', cn_name: '新西兰', code: '554' },
  { name: 'Oman', cn_name: '阿曼', code: '512' },
  { name: 'Pakistan', cn_name: '巴基斯坦', code: '586' },
  { name: 'Panama', cn_name: '巴拿马', code: '591' },
  { name: 'Peru', cn_name: '秘鲁', code: '604' },
  { name: 'Philippines', cn_name: '菲律宾', code: '608' },
  { name: 'Palau', cn_name: '帕劳', code: '585' },
  { name: 'Papua New Guinea', cn_name: '巴布亚新几内亚', code: '598' },
  { name: 'Poland', cn_name: '波兰', code: '616' },
  { name: 'Puerto Rico', cn_name: '波多黎各', code: '630' },
  { name: "Democratic People's Republic of Korea", cn_name: '朝鲜', code: '408' },
  { name: 'Portugal', cn_name: '葡萄牙', code: '620' },
  { name: 'Paraguay', cn_name: '巴拉圭', code: '600' },
  { name: 'State of Palestine', cn_name: '巴勒斯坦', code: '275' },
  { name: 'French Polynesia', cn_name: '法属波利尼西亚', code: '258' },
  { name: 'Qatar', cn_name: '卡塔尔', code: '634' },
  { name: 'Romania', cn_name: '罗马尼亚', code: '642' },
  { name: 'Russian Federation', cn_name: '俄罗斯', code: '643' },
  { name: 'Rwanda', cn_name: '卢旺达', code: '646' },
  { name: 'Saudi Arabia', cn_name: '沙特阿拉伯', code: '682' },
  { name: 'Sudan', cn_name: '苏丹', code: '729' },
  { name: 'South Sudan', cn_name: '南苏丹', code: '728' },
  { name: 'Senegal', cn_name: '塞内加尔', code: '686' },
  { name: 'Singapore', cn_name: '新加坡', code: '702' },
  { name: 'South Georgia and the South Sandwich Islands', cn_name: '南乔治亚岛', code: '239' },
  { name: 'Saint Helena, Ascension and Tristan da Cunha', cn_name: '圣赫勒拿', code: '654' },
  { name: 'Solomon Islands', cn_name: '所罗门群岛', code: '090' },
  { name: 'Sierra Leone', cn_name: '塞拉利昂', code: '694' },
  { name: 'El Salvador', cn_name: '萨尔瓦多', code: '222' },
  { name: 'Saint Pierre and Miquelon', cn_name: '圣皮埃尔和密克隆', code: '666' },
  { name: 'Sao Tome and Principe', cn_name: '圣多美和普林西比', code: '678' },
  { name: 'Suriname', cn_name: '苏里南', code: '740' },
  { name: 'Slovakia', cn_name: '斯洛伐克', code: '703' },
  { name: 'Slovenia', cn_name: '斯洛文尼亚', code: '705' },
  { name: 'Sweden', cn_name: '瑞典', code: '752' },
  { name: 'Eswatini', cn_name: '斯威士兰', code: '748' },
  { name: 'Seychelles', cn_name: '塞舌尔', code: '690' },
  { name: 'Syrian Arab Republic', cn_name: '叙利亚', code: '760' },
  { name: 'Turks and Caicos Islands', cn_name: '特克斯和凯科斯群岛', code: '796' },
  { name: 'Chad', cn_name: '乍得', code: '148' },
  { name: 'Togo', cn_name: '多哥', code: '768' },
  { name: 'Thailand', cn_name: '泰国', code: '764' },
  { name: 'Tajikistan', cn_name: '塔吉克斯坦', code: '762' },
  { name: 'Turkmenistan', cn_name: '土库曼斯坦', code: '795' },
  { name: 'Timor-Leste', cn_name: '东帝汶', code: '626' },
  { name: 'Tonga', cn_name: '汤加', code: '776' },
  { name: 'Trinidad and Tobago', cn_name: '特立尼达和多巴哥', code: '780' },
  { name: 'Tunisia', cn_name: '突尼斯', code: '788' },
  { name: 'Turkey', cn_name: '土耳其', code: '792' },
  { name: 'United Republic of Tanzania', cn_name: '坦桑尼亚', code: '834' },
  { name: 'Uganda', cn_name: '乌干达', code: '800' },
  { name: 'Ukraine', cn_name: '乌克兰', code: '804' },
  { name: 'Uruguay', cn_name: '乌拉圭', code: '858' },
  { name: 'United States of America', cn_name: '美国', code: '840' },
  { name: 'Uzbekistan', cn_name: '乌兹别克斯坦', code: '860' },
  { name: 'Saint Vincent and the Grenadines', cn_name: '圣文森特和格林纳丁斯', code: '670' },
  { name: 'Venezuela, Bolivarian Republic of', cn_name: '委内瑞拉', code: '862' },
  { name: 'Virgin Islands, U.S.', cn_name: '美属维尔京群岛', code: '850' },
  { name: 'Vietnam', cn_name: '越南', code: '704' },
  { name: 'Vanuatu', cn_name: '瓦努阿图', code: '548' },
  { name: 'Samoa', cn_name: '萨摩亚', code: '882' },
  { name: 'Yemen', cn_name: '也门', code: '887' },
  { name: 'South Africa', cn_name: '南非', code: '710' },
  { name: 'Zambia', cn_name: '赞比亚', code: '894' },
  { name: 'Zimbabwe', cn_name: '津巴布韦', code: '716' },
  { name: 'San Marino', cn_name: '圣马力诺', code: '674' },
  { name: 'Holy See (Vatican City State)', cn_name: '梵蒂冈', code: '336' },
  { name: 'Monaco', cn_name: '摩纳哥', code: '492' },
  { name: 'Maldives', cn_name: '马尔代夫', code: '462' },
  { name: 'Marshall Islands', cn_name: '马绍尔群岛', code: '584' },
  { name: 'Nauru', cn_name: '瑙鲁', code: '520' },
  { name: 'Tokelau', cn_name: '托克劳', code: '772' },
  { name: 'Cook Islands', cn_name: '库克群岛', code: '184' },
  { name: 'Saint Kitts and Nevis', cn_name: '圣基茨和尼维斯', code: '659' },
  { name: 'Tuvalu', cn_name: '图瓦卢', code: '798' }
]
