CREATE TABLE IF NOT EXISTS `notice`(
   `EVENT` VARCHAR(100) NOT NULL,
   `TEST_ID` VARCHAR(100) NOT NULL,
   `NAME` VARCHAR(100) NOT NULL,
   `EMAIL` VARCHAR(100) NOT NULL,
	 `ENABLE` VARCHAR(40) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

