UPDATE `my_plugin`
SET `version` = '1.18.2'
where `plugin_id` > 0
  and `version` = '1.18.1';

UPDATE `sys_menu`
SET `pid` = 8
WHERE `menu_id` = 800;

INSERT INTO `sys_menu` (`menu_id`,
                        `pid`,
                        `sub_count`,
                        `type`,
                        `title`,
                        `name`,
                        `component`,
                        `menu_sort`,
                        `icon`,
                        `path`,
                        `i_frame`,
                        `cache`,
                        `hidden`,
                        `permission`,
                        `create_by`,
                        `update_by`,
                        `create_time`,
                        `update_time`)
VALUES (802,
        0,
        0,
        2,
        '视图导出',
        NULL,
        NULL,
        999,
        NULL,
        NULL,
        0,
        0,
        0,
        'view:export',
        NULL,
        NULL,
        NULL,
        NULL);

INSERT INTO `sys_auth` (`id`,
                        `auth_source`,
                        `auth_source_type`,
                        `auth_target`,
                        `auth_target_type`,
                        `auth_time`,
                        `auth_details`,
                        `auth_user`,
                        `update_time`,
                        `copy_from`,
                        `copy_id`)
VALUES ('dc3536c2-5193-4fcd-a875-926e3e712344',
        '802',
        'menu',
        '2',
        'role',
        1673405964319,
        NULL,
        'admin',
        NULL,
        NULL,
        NULL);
INSERT INTO `sys_auth` (`id`,
                        `auth_source`,
                        `auth_source_type`,
                        `auth_target`,
                        `auth_target_type`,
                        `auth_time`,
                        `auth_details`,
                        `auth_user`,
                        `update_time`,
                        `copy_from`,
                        `copy_id`)
VALUES ('dc7fa546-9ac4-49a7-8af2-152be9fdde68',
        '802',
        'menu',
        '1',
        'role',
        1673405986872,
        NULL,
        'admin',
        NULL,
        NULL,
        NULL);
INSERT INTO `sys_auth_detail` (`id`,
                               `auth_id`,
                               `privilege_name`,
                               `privilege_type`,
                               `privilege_value`,
                               `privilege_extend`,
                               `remark`,
                               `create_user`,
                               `create_time`,
                               `update_time`,
                               `copy_from`,
                               `copy_id`)
VALUES ('01c6367b-915c-11ed-bd88-0242ac130004',
        'dc7fa546-9ac4-49a7-8af2-152be9fdde68',
        'i18n_auth_grant',
        15,
        0,
        'grant',
        '基础权限-授权',
        'admin',
        1673405987000,
        NULL,
        NULL,
        NULL);
INSERT INTO `sys_auth_detail` (`id`,
                               `auth_id`,
                               `privilege_name`,
                               `privilege_type`,
                               `privilege_value`,
                               `privilege_extend`,
                               `remark`,
                               `create_user`,
                               `create_time`,
                               `update_time`,
                               `copy_from`,
                               `copy_id`)
VALUES ('01c63c6c-915c-11ed-bd88-0242ac130004',
        'dc7fa546-9ac4-49a7-8af2-152be9fdde68',
        'i18n_auth_use',
        1,
        1,
        'use',
        '基础权限-使用',
        'admin',
        1673405987000,
        NULL,
        NULL,
        NULL);
INSERT INTO `sys_auth_detail` (`id`,
                               `auth_id`,
                               `privilege_name`,
                               `privilege_type`,
                               `privilege_value`,
                               `privilege_extend`,
                               `remark`,
                               `create_user`,
                               `create_time`,
                               `update_time`,
                               `copy_from`,
                               `copy_id`)
VALUES ('f4559db9-915b-11ed-bd88-0242ac130004',
        'dc3536c2-5193-4fcd-a875-926e3e712344',
        'i18n_auth_grant',
        15,
        0,
        'grant',
        '基础权限-授权',
        'admin',
        1673405964000,
        NULL,
        NULL,
        NULL);
INSERT INTO `sys_auth_detail` (`id`,
                               `auth_id`,
                               `privilege_name`,
                               `privilege_type`,
                               `privilege_value`,
                               `privilege_extend`,
                               `remark`,
                               `create_user`,
                               `create_time`,
                               `update_time`,
                               `copy_from`,
                               `copy_id`)
VALUES ('f455a074-915b-11ed-bd88-0242ac130004',
        'dc3536c2-5193-4fcd-a875-926e3e712344',
        'i18n_auth_use',
        1,
        1,
        'use',
        '基础权限-使用',
        'admin',
        1673405964000,
        NULL,
        NULL,
        NULL);
