/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const ElForm: typeof import('element-plus-secondary/es')['ElForm']
  const ElFormItem: typeof import('element-plus-secondary/es')['ElFormItem']
  const ElInput: typeof import('element-plus-secondary/es')['ElInput']
  const ElMessageBox: typeof import('element-plus-secondary/es')['ElMessageBox']
}
