/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AceEditor: typeof import('./src/components/data-visualization/canvas/AceEditor.vue')['default']
    Area: typeof import('./src/components/data-visualization/canvas/Area.vue')['default']
    Canvas: typeof import('./src/components/data-visualization/canvas/index.vue')['default']
    CanvasAttr: typeof import('./src/components/data-visualization/CanvasAttr.vue')['default']
    ColumnList: typeof import('./src/components/column-list/src/ColumnList.vue')['default']
    ComponentList: typeof import('./src/components/data-visualization/ComponentList.vue')['default']
    ComponentWrapper: typeof import('./src/components/data-visualization/canvas/ComponentWrapper.vue')['default']
    ConfigGlobal: typeof import('./src/components/config-global/src/ConfigGlobal.vue')['default']
    ContextMenu: typeof import('./src/components/data-visualization/canvas/ContextMenu.vue')['default']
    DrawerFilter: typeof import('./src/components/drawer-filter/src/DrawerFilter.vue')['default']
    DrawerMain: typeof import('./src/components/drawer-main/src/DrawerMain.vue')['default']
    ElButton: typeof import('element-plus-secondary/es')['ElButton']
    ElCheckbox: typeof import('element-plus-secondary/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus-secondary/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus-secondary/es')['ElCol']
    ElDialog: typeof import('element-plus-secondary/es')['ElDialog']
    ElDivider: typeof import('element-plus-secondary/es')['ElDivider']
    ElDropdown: typeof import('element-plus-secondary/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus-secondary/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus-secondary/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus-secondary/es')['ElForm']
    ElFormItem: typeof import('element-plus-secondary/es')['ElFormItem']
    ElIcon: typeof import('element-plus-secondary/es')['ElIcon']
    ElInput: typeof import('element-plus-secondary/es')['ElInput']
    ElOption: typeof import('element-plus-secondary/es')['ElOption']
    ElRow: typeof import('element-plus-secondary/es')['ElRow']
    ElSelect: typeof import('element-plus-secondary/es')['ElSelect']
    ElSwitch: typeof import('element-plus-secondary/es')['ElSwitch']
    ElTableColumn: typeof import('element-plus-secondary/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus-secondary/es')['ElTabPane']
    ElTabs: typeof import('element-plus-secondary/es')['ElTabs']
    ElTree: typeof import('element-plus-secondary/es')['ElTree']
    EventList: typeof import('./src/components/data-visualization/EventList.vue')['default']
    FilterText: typeof import('./src/components/filter-text/src/FilterText.vue')['default']
    Grid: typeof import('./src/components/data-visualization/canvas/Grid.vue')['default']
    GridTable: typeof import('./src/components/grid-table/src/GridTable.vue')['default']
    HandleMore: typeof import('./src/components/handle-more/src/HandleMore.vue')['default']
    Icon: typeof import('./src/components/icon-custom/src/Icon.vue')['default']
    MarkLine: typeof import('./src/components/data-visualization/canvas/MarkLine.vue')['default']
    Modal: typeof import('./src/components/data-visualization/Modal.vue')['default']
    Preview: typeof import('./src/components/data-visualization/canvas/Preview.vue')['default']
    RealTimeComponentList: typeof import('./src/components/data-visualization/RealTimeComponentList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shape: typeof import('./src/components/data-visualization/canvas/Shape.vue')['default']
    TableBody: typeof import('./src/components/grid-table/src/TableBody.vue')['default']
    Toolbar: typeof import('./src/components/data-visualization/Toolbar.vue')['default']
  }
}
