export const SPREADSHEET_EVENTS = {
  OPEN_PLUGIN_EDITOR: 'OPEN_PLUGIN_EDITOR',
  CLOSE_PLUGIN_EDITOR: 'CLOSE_PLUGIN_EDITOR',
  SHOW_PLUGIN_ACTION_TOOLBAR: 'SHOW_PLUGIN_ACTION_TOOLBAR',
  HIDE_PLUGIN_ACTION_TOOLBAR: 'HIDE_PLUGIN_ACTION_TOOLBAR',
  COPY_PLUGIN_TABLE: 'COPY_PLUGIN_TABLE',
  CUT_PLUGIN_TABLE: 'CUT_PLUGIN_TABLE',
  DELETE_PLUGIN_RENDER: 'DELETE_PLUGIN_RENDER',
  REFRESH_PLUGIN_DATA: 'REFRESH_PLUGIN_DATA',
  OPEN_COMPONENT_DATASET_REPLACEMENT: 'OPEN_COMPONENT_DATASET_REPLACEMENT',
  DATASET_REPLACEMENT_COMPLETED: 'DATASET_REPLACEMENT_COMPLETED',
  CELL_SELECTED: 'CELL_SELECTED',
  PLACEHOLDER_TOOLTIP_SHOW: 'PLACEHOLDER_TOOLTIP_SHOW',
  PLACEHOLDER_TOOLTIP_HIDE: 'PLACEHOLDER_TOOLTIP_HIDE'
} as const
