spring:
  datasource:
    url: jdbc:dm://hostname:5236
    username: user
    password: passwd
    driver-class-name: dm.jdbc.driver.DmDriver
  jpa:
    properties:
      hibernate:
        dialect: io.dataease.config.CustomDMDialect
        auto_quote_keyword: false
        globally_quoted_identifiers: true
        jdbc:
          batch_size: 1000
          lob:
            non_contextual_creation: true
        order_inserts: true
        order_updates: true
        temp:
          use_jdbc_metadata_defaults: false
        default_schema: SYSDBA
    hibernate:
      naming:
        physical-strategy:  io.dataease.config.DynamicCaseNamingStrategy
      ddl-auto: update
    show-sql: false


quartz:
  enabled: true
  scheduler-name: deSyncJob
