spring:
  datasource:
    url: jdbc:dm://hostname:5236
    username: user
    password: passwd
    driver-class-name: dm.jdbc.driver.DmDriver
  messages:
    basename: i18n/lic,i18n/core,i18n/permissions,i18n/xpack,i18n/sync
  flyway:
    enabled: false
  jpa:
    properties:
      hibernate:
        dialect: io.dataease.config.CustomDMDialect
        auto_quote_keyword: false
        jdbc:
          batch_size: 1000
          lob:
            non_contextual_creation: true
        order_inserts: true
        order_updates: true
        temp:
          use_jdbc_metadata_defaults: false
        default_schema: SYSDBA
    hibernate:
      naming:
        physical-strategy:  io.dataease.config.DynamicCaseNamingStrategy
      ddl-auto: update
    show-sql: true


quartz:
  enabled: true
  scheduler-name: deSyncJob
#  properties.org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
