spring:
  datasource:
    url: jdbc:postgresql://hostname:5432/dataease?currentSchema=de3
    username: dataease
    password: passwd
    driver-class-name: org.postgresql.Driver
  flyway:
      enabled: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 1000
          lob:
            non_contextual_creation: true
        order_inserts: true
        order_updates: true
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      naming:
        physical-strategy:  io.dataease.config.DynamicCaseNamingStrategy
      ddl-auto: update
    show-sql: true

quartz:
  enabled: true
  scheduler-name: deSyncJob
  properties.org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
