spring:
  datasource:
    url: jdbc:sqlserver://hostname:1433;DatabaseName=f2c_test_data;currentSchema=jinlong;encrypt=false
    username: sa
    password: Calong@2015
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  flyway:
      enabled: false

  jpa:
    properties:
      hibernate:
        dialect: io.dataease.config.CustomSQLServerDialect
        jdbc:
          batch_size: 1000
          lob:
            non_contextual_creation: true
        order_inserts: true
        order_updates: true
        temp:
          use_jdbc_metadata_defaults: false
        default_schema: jinlong
    hibernate:
      naming:
        physical-strategy:  io.dataease.config.DynamicCaseNamingStrategy
      ddl-auto: update
    show-sql: false

quartz:
  enabled: true
  scheduler-name: deSyncJob
  properties.org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.MSSQLDelegate

